server {
  listen 80;
  server_name _;

  # SPA (Vite/React)
  root  /usr/share/nginx/html;
  index index.html;

  # -------- PROXY /api -> FastAPI -----------
  # match /api y /api/... sin romper /api solo
  location ~ ^/api(/|$) {
    # si querés que al backend le llegue /events, /categories, etc (sin /api)
    rewrite ^/api/?(.*)$ /$1 break;

    proxy_pass         http://backend:8000;
    proxy_http_version 1.1;

    proxy_set_header Host              $host;
    proxy_set_header X-Real-IP         $remote_addr;
    proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  # Health del front (opcional)
  location = /healthz {
    return 200 '{"status":"ok"}';
    add_header Content-Type application/json;
  }

  # SPA fallback (no pises /api)
  location / {
    try_files $uri /index.html;
  }
}