apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: ticketpardo
  labels:
    app: backend
    component: api
spec:
  selector:
    app: backend
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    nodePort: 30000
    protocol: TCP
  type: NodePort
